version: '3.6'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    restart: unless-stopped
    ports:
    - "5439:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: tranmas

  graphql-engine:
    image: hasura/graphql-engine:v1.3.2
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/tranmas
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  adminer:     
    container_name: adminer_jwt        
    image: adminer     
    restart: unless-stopped     
    ports:       
    - 8565:8080

  webflask:
    container_name: webflask
    build: ./backend-python
    volumes: 
      - ./images:/code/images
    ports:
    - "5000:5000"

volumes:
  db_data:

