version: "3.6"
services:
  postgres:
    container_name: postgres
    image: postgres:12
    restart: unless-stopped
    ports:
      - "5439:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: tranmas

  graphql-engine:
    image: hasura/graphql-engine:v1.3.2
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/tranmas
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  adminer:
    container_name: adminer_jwt
    image: adminer
    restart: unless-stopped
    ports:
      - 8565:8080
    # SERVIDOR DE IMAGENES ESCRITO EN PYTHON
  webflask:
    container_name: webflask
    restart: unless-stopped
    build: ./backend-python
    volumes:
      - ./images:/code/images
      - ./imagenes-accidentes/:/code/imagenes-accidentes
      - ./imagenes-daños-edificios:/code/imagenes-daños-edificios
      - ./archivos-contratos:/code/archivos-contratos
    ports:
      - "5000:5000"

  frontend:
    container_name: frontend
    build: ./frontend
    expose:
      - "5000"
    volumes:
      - ./frontend/frontend:/usr/src/app

  # SERVIDOR NGINX QUE DISTRUYE EL TRAFICO A LOS DISTINTOS CONTENEDORES
  nginx_proxy:
    build: ./nginx
    ports:
      - 80:80
    links:
      - frontend
      - graphql-engine
      - webflask
    restart: always