export const REGISTRO = 'REGISTRO';
export const OBTENER_EMPLEADOS = 'OBTENER_EMPLEADOS';
export const AGREGAR_EMPLEADO = 'AGREGAR_EMPLEADO'
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';

export const OBTENER_REPUESTOS = 'OBTENER_REPUESTOS';
export const GUARDAR_REPUESTOS = 'GUARDAR_REPUESTOS';