export const FORMULARIO_REGISTROS = 'REGISTRO';
export const OBTENER_EMPLEADOS = 'OBTENER_REGISTROS';
export const AGREGAR_EMPLEADO = 'AGREGAR_EMPLEADO'
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';